import {
  FaSyringe,
  FaVials,
  FaPrescriptionBottle,
  FaWeightHanging,
  FaStar,
  FaWaveSquare,
  FaTint,
  FaSun,
  FaSnowflake,
  FaUserMd,
  FaPenFancy,
  FaPenNib,
  FaEye,
  FaCircle,
  FaBandAid,
  FaLayerGroup,
} from "react-icons/fa";
import {
  MdSpa,
  MdPrecisionManufacturing,
  MdFace6,
  MdFaceRetouchingNatural,
} from "react-icons/md";
import {
  GiSyringe,
  GiTargetLaser,
  GiTargetArrows,
  GiTargetShot,
  GiTargeted,
  GiOrbWand,
  GiDna1,
  GiHairStrands,
  GiStitchedWound,
  GiScarWound,
  GiScalpel,
  GiSewingString,
  GiWaves,
  GiSunRadiations,
  GiTensionSnowflake,
  GiLaserGun,
} from "react-icons/gi";

const iconMap = {
  // Hair restoration - unique icons for each
  hair: GiHairStrands,
  vial: FaVials,
  cell: GiDna1,
  laser: GiTargetLaser,
  needle: FaSyringe,
  wave: FaWaveSquare,
  drop: FaTint,
  sparkle: FaStar,
  face: MdFace6,
  layers: FaLayerGroup,
  pen: FaPenFancy,
  eye: FaEye,
  spot: FaCircle,
  ear: FaUserMd,
  patch: FaBandAid,
  sun: FaSun,
  snow: FaSnowflake,
  iv: FaPrescriptionBottle,
  thread: FaWeightHanging,
  device: MdPrecisionManufacturing,
  hydra: MdSpa,
  syringe: FaSyringe,
  // Additional mappings for specific treatments - ALL UNIQUE
  "prp": GiSyringe,
  "gfc": FaVials,
  "exosome": GiDna1,
  "fue": GiHairStrands,
  "lllt": GiTargetLaser,
  "mesotherapy": FaSyringe,
  "hair-botox": MdSpa,
  "hair-booster": FaTint,
  "acne-management": MdFace6,
  "chemical-peels": FaLayerGroup,
  "pico-carbon": GiTargetArrows,
  "mnrf": FaWaveSquare,
  "fractional-co2": GiTargetShot,
  "qyag": GiTargeted,
  "dermapen": FaPenFancy,
  "subcision": GiScalpel,
  "skin-boosters": FaTint,
  "pdrn": GiStitchedWound,
  "led": FaSun,
  "botox": GiSyringe,
  "fillers": FaTint,
  "thread-lift": FaWeightHanging,
  "hifu": FaWaveSquare,
  "apollo": MdPrecisionManufacturing,
  "mnrf-tightening": GiWaves,
  "under-eye": FaEye,
  "mole-removal": GiScalpel,
  "ear-lobe": FaUserMd,
  "vitiligo": GiScarWound,
  "phototherapy": GiSunRadiations,
  "cryotherapy": GiTensionSnowflake,
  "microblading": FaPenFancy,
  "laser-hair-removal": GiLaserGun,
  "laser-toning": GiTargetLaser,
  "carbon-peel": GiTargetArrows,
  "tattoo-removal": GiTargetShot,
  "fractional-resurfacing": GiTargeted,
  "hydrafacial": MdSpa,
  "hydra-touch": MdFaceRetouchingNatural,
  "microdermabrasion": FaPenNib,
  "microneedling": GiSewingString,
  "iv-glutathione": FaPrescriptionBottle,
  "dr-platon": GiOrbWand,
  // More unique mappings
  "acne-scar": GiStitchedWound,
  "pico-toning": GiTargetArrows,
  "carbon-toning": GiTargetArrows,
  "fractional-co2-qyag": GiTargetShot,
  "dermapen-intl": FaPenFancy,
  "led-phototherapy": FaSun,
  "skin-boosters-pdrn-exosomes": GiStitchedWound,
  "cold-plasma": GiOrbWand,
  "botox-wrinkle": GiSyringe,
  "dermal-fillers": FaTint,
  "thread-lifts": FaWeightHanging,
  "hifu-lifting": FaWaveSquare,
  "apollo-quattro": MdPrecisionManufacturing,
  "mnrf-tightening-anti": GiWaves,
  "pdrn-therapy": GiStitchedWound,
  "skin-boosters-anti": FaTint,
  "under-eye-rejuvenation": FaEye,
  "mole-skin-tag-cyst": GiScalpel,
  "ear-lobe-repair": FaUserMd,
  "vitiligo-grafting": GiScarWound,
  "phototherapy-nb-uvb": GiSunRadiations,
  "cryo-electrocautery": GiTensionSnowflake,
  "microblading-dermoscopy": FaPenFancy,
  "laser-hair-removal-diode": GiLaserGun,
  "laser-toning-pigmentation": GiTargetLaser,
  "carbon-laser-peel": GiTargetArrows,
  "tattoo-removal-q": GiTargetShot,
  "fractional-co2-resurfacing": GiTargeted,
};

export function getTreatmentIconComponent(iconName) {
  const Component = iconMap[iconName] || FaStar;
  return Component;
}

export function TreatmentIcon({ name, size = 28, className = "", color = "currentColor" }) {
  const Component = getTreatmentIconComponent(name);
  return <Component className={className} size={size} color={color} aria-hidden="true" />;
}

export default TreatmentIcon;